import {ResourceModel} from "../../crm/models/core/resource.model";
import {PersonnePhysique} from "../../crm/models/personne/personne.physique.model";
import {Ville} from "../../crm/models/ville.model";
import {Pays} from "../../crm/models/pays.model";
import {FormeJuridiqueOpc} from "./forme-juridique-opc";
import {Emetteur} from "./emetteur";
import {Registraire} from "./registraire";
import {TypeAffectationTitre} from "./type-affectation-vl";

export class Opcvm extends ResourceModel<Opcvm> {
  idOpcvm: number = 0;
  ibOpcvm: string = "";
  agrement: string = "";
  dateAgrement: any = null;
  registreDeCommerce: string = "";
  estCompteSysteme: boolean = false;
  personneGestionnaire: PersonnePhysique | null = null;
  codeFormeJuridique: string = "";
  formeJuridiqueOpc: FormeJuridiqueOpc | null;
  personneIntervenant: Registraire | null;
  typeAffectationTitre: TypeAffectationTitre | null;
  personneEmetteur: Emetteur | null;
  classification: any;
  dateCreationOpcvm: any = new Date();
  sigleOpcvm: string = "";
  denominationOpcvm: string = "";
  nbrePartInitial: number = 0;
  nbrePartDebutExercice: number = 0;
  nbrePartActuelle: number = 0;
  valeurLiquidativeOrigine: number = 0;
  valeurLiquidativeActuelle: number = 0;
  capitalInitialOpcvm: number = 0;
  coursInitial: 'CONNU' | 'INCONNU';
  coursActuel: 'CONNU' | 'INCONNU';
  dureeExerciceOpcvm: number = 0;
  debutExerciceActuelOpcvm: any = null;
  uniteDureeExerciceOpcvm: string = "";
  periodiciteAffectationOpcvm: number = 0;
  unitePeriodiciteAffectationOpcvm: string = "";
  derniereDateAffectationOpcvm: any = null;
  periodiciteCalculValeurLiquidativeOpcvm: number = 0;
  unitePeriodiciteCalculValeurLiquidative: string = "";
  valeurMinimalPlacement: number = 0;
  dureeMinimalPlacement: number = 0;
  uniteDureeMinimalPlacement: string = "";
  dateProchainCalculVL: any = null;
  appliqueeTVA: boolean = false;
  appliqueeTAF: boolean = false;
  nombreDecimaux: number = 0;
  estArrondiSupInf: boolean = false;
  nombreDecimauxCompta: number = 0;
  estArrondiSupInfCompta: boolean = false;
  nombreDecimauxPart: number = 0;
  tauxCommissionSouscription: number = 0;
  tauxCommissionRachat: number = 0;
  tauxTAF: number = 0;
  tauxRetrocessionSouscription: number = 0;
  tauxRetrocessionRachat: number = 0;
  tauxFraisGestion: number = 0;
  appliquerSurActifNet: boolean = false;
  delaiLivraisonOpcvm: number = 0;
  uniteDelaiLivraisonOpcvm: string = "";
  nomContact: string = "";
  prenomContact: string = "";
  adresseContact: string = "";
  borneInferieureSensibilite: number = 0;
  borneSuperieureSensibilite: number = 0;
  inclusBorneInferieureSensibilite: boolean = false;
  inclusBorneSuperieureSensibilite: boolean = false;
  visaNoteInformation: string = "";
  verifier: boolean = false;
  verifierNiveau1: boolean = false;
  verifierNiveau2: boolean = false;
  verificateur1: string = "";
  verificateur2: string = "";
  dateVerifNiveau1: string = "";
  dateVerifNiveau2: string = "";
  cheminArchive: string = "";
  adresseComplete: string = "";
  telephoneFixe: string = "";
  telephoneMobile: string = "";
  codeSkype: string = "";
  siteweb: string = "";
  fax: string = "";
  email: string = "";
  boitePostale: string = "";
  pays: Pays | null = null;
  ville: Ville | null = null;
  tauxRendement: number = 0;
  titre: any = null;
  dateCreationServeur: any = new Date();
  dateDernModifServeur: any = null;
  dateDernModifClient: any = null;
  numLigne: number = 0;
  supprimer: boolean = false;
  userLogin: string = "";

  constructor(model?: Partial<Opcvm>) {
    super(model);
  }
}
